"""Deterministic provider for tests and key-less demo runs. It replays
fixtures generated by scripts/make_corpus.py, keyed by sha256 of the
normalized document text — the same interface and the same downstream
verification as the live provider. Unknown documents get an honest
'unknown' classification and zero facts, which exercises the escalation
path rather than hiding it.

The call log (a plain file) lets tests count real invocations across
process kills — that is how resume-without-rework is proven.
"""
import hashlib
import json
import os
import time

from .. import config
from .boundary import Classification, Extraction, LLMResult


class MockProvider:
    name = "mock"

    def __init__(self) -> None:
        import pathlib

        fixtures_dir = pathlib.Path(
            os.environ.get("FIXTURES_DIR", str(config.FIXTURES_DIR))
        )
        path = fixtures_dir / "extractions.json"
        self.fixtures = json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}
        self.call_log = os.environ.get("MOCK_LLM_CALL_LOG")
        self.delay_ms = int(os.environ.get("MOCK_LLM_DELAY_MS", "0"))

    def _log(self, op: str, sha: str) -> None:
        if self.delay_ms:
            time.sleep(self.delay_ms / 1000)
        if self.call_log:
            with open(self.call_log, "a", encoding="utf-8") as f:
                f.write(f"{op}\t{sha}\t{time.time()}\n")

    def _fixture(self, text: str) -> tuple[str, dict | None]:
        sha = hashlib.sha256(text.encode("utf-8")).hexdigest()
        return sha, self.fixtures.get(sha)

    def classify(self, text: str) -> LLMResult:
        sha, fx = self._fixture(text)
        self._log("classify", sha)
        if fx is None:
            data = Classification(
                doc_class="unknown", entity="unknown", doc_date=None,
                confidence=0.0, instruction_like=False,
            )
        else:
            data = Classification(**fx["classify"])
        return LLMResult(data=data, provider=self.name, model="mock", latency_ms=1)

    def extract(self, text: str, classification: Classification) -> LLMResult:
        sha, fx = self._fixture(text)
        self._log("extract", sha)
        facts = fx["facts"] if fx else []
        return LLMResult(
            data=Extraction(facts=facts),
            provider=self.name, model="mock", latency_ms=1,
        )
